"""empty message

Revision ID: 115cfc28c0bb
Revises: c38d6dc4240d
Create Date: 2022-02-18 16:35:19.388099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115cfc28c0bb'
down_revision = 'c38d6dc4240d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pantry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=28), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('unit', sa.String(length=15), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pantry')
    # ### end Alembic commands ###
