"""empty message

Revision ID: 540e6a9e1a42
Revises: fc6fcfb339b4
Create Date: 2022-02-18 17:50:27.739294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540e6a9e1a42'
down_revision = 'fc6fcfb339b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'pantry', 'book', ['recipe_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pantry', type_='foreignkey')
    # ### end Alembic commands ###
