"""empty message

Revision ID: 823df8b4b33e
Revises: fa0a7e72e93f
Create Date: 2022-02-17 18:36:19.443138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823df8b4b33e'
down_revision = 'fa0a7e72e93f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('broccoli', sa.Boolean(), nullable=True))
    op.add_column('book', sa.Column('cauli', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'cauli')
    op.drop_column('book', 'broccoli')
    # ### end Alembic commands ###
