"""empty message

Revision ID: fc6fcfb339b4
Revises: 115cfc28c0bb
Create Date: 2022-02-18 17:42:07.509045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc6fcfb339b4'
down_revision = '115cfc28c0bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pantry_ibfk_1', 'pantry', type_='foreignkey')
    op.create_foreign_key(None, 'pantry', 'book', ['recipe_id'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pantry', type_='foreignkey')
    op.create_foreign_key('pantry_ibfk_1', 'pantry', 'book', ['recipe_id'], ['id'])
    # ### end Alembic commands ###
